// This file is free software; you can redistribute it and/or modify it under
// the terms of the GNU General Public License version 2, 1991 as published by
// the Free Software Foundation.
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
// details.
// A copy of the GNU General Public License can be found at:
// http://www.gnu.org/licenses/gpl.html
// a collection of item methods
object Item2 {
    var Runerock: IntArray = intArrayOf(
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.UNCUT_SAPPHIRE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.UNCUT_DIAMOND,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.UNCUT_EMERALD,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.UNCUT_RUBY,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE,
        ItemIDs.RUNITE_ORE
    )

    fun randomRuneRock(): Int {
        return Runerock[(Math.random() * Runerock.size).toInt()]
    }

    var present: IntArray = intArrayOf(
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        15340,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        15341,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        15342,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        15343,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS
    )

    fun randompresent(): Int {
        return present[(Math.random() * present.size).toInt()]
    }

    var flowers: IntArray = intArrayOf(2980, 2981, 2982, 2983, 2984, 2985, 2986, 2987, 2988)

    fun randomflowers(): Int {
        return flowers[(Math.random() * flowers.size).toInt()]
    }

    var balloon: IntArray = intArrayOf(115, 116, 117, 118, 119, 120, 121, 122)

    @JvmStatic
    fun randomballoon(): Int {
        return balloon[(Math.random() * balloon.size).toInt()]
    }

    var corp: IntArray = intArrayOf(
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        13734,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        13754,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        13746,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        13748,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        13748,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        13750,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        13752,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
    )

    fun randomcorp(): Int {
        return corp[(Math.random() * corp.size).toInt()]
    }

    var coalrock: IntArray = intArrayOf(
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.UNCUT_SAPPHIRE,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.UNCUT_DIAMOND,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.UNCUT_EMERALD,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.UNCUT_RUBY,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL,
        ItemIDs.COAL
    )

    fun randomCoalRock(): Int {
        return coalrock[(Math.random() * coalrock.size).toInt()]
    }

    var daggy: IntArray = intArrayOf()

    fun randomdaggy(): Int {
        return daggy[(Math.random() * daggy.size).toInt()]
    }

    var whiteknight: IntArray = intArrayOf(
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.WHITE_CLAWS,
        6589,
        6591,
        6599,
        6601,
        6605,
        6607,
        6609,
        6611,
        6613,
        6615,
        6617,
        6619,
        6621,
        6623,
        6625,
        6627,
        6629,
        6631,
        6633,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS
    )

    @JvmStatic
    fun randomwhiteknight(): Int {
        return whiteknight[(Math.random() * whiteknight.size).toInt()]
    }

    var easteregg: IntArray = intArrayOf(7928, 7929, 7930, 7931, 7932, 7933)

    fun randomeastergg(): Int {
        return easteregg[(Math.random() * easteregg.size).toInt()]
    }

    var Copperrock: IntArray = intArrayOf(
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.UNCUT_SAPPHIRE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.UNCUT_DIAMOND,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.UNCUT_EMERALD,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.UNCUT_RUBY,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE,
        ItemIDs.COPPER_ORE
    )

    fun randomCopperRock(): Int {
        return Copperrock[(Math.random() * Copperrock.size).toInt()]
    }

    var Tinrock: IntArray = intArrayOf(
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.UNCUT_SAPPHIRE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.UNCUT_DIAMOND,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.UNCUT_EMERALD,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.UNCUT_RUBY,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE,
        ItemIDs.TIN_ORE
    )

    fun randomTinRock(): Int {
        return Tinrock[(Math.random() * Tinrock.size).toInt()]
    }

    var Ironrock: IntArray = intArrayOf(
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.UNCUT_SAPPHIRE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.UNCUT_DIAMOND,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.UNCUT_EMERALD,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.UNCUT_RUBY,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE,
        ItemIDs.IRON_ORE
    )

    fun randomIronRock(): Int {
        return Ironrock[(Math.random() * Ironrock.size).toInt()]
    }

    var Phat: IntArray = intArrayOf(
        ItemIDs.RED_PARTYHAT,
        ItemIDs.YELLOW_PARTYHAT,
        ItemIDs.BLUE_PARTYHAT,
        ItemIDs.GREEN_PARTYHAT,
        ItemIDs.PURPLE_PARTYHAT,
        ItemIDs.WHITE_PARTYHAT,
        ItemIDs.UNKNOWED_WHITE_PARTYHAT,
        14560,
        14110,
        14111,
        14112,
        14113,
        14114,
        14115,
        14116,
        14117,
        14118,
    )

    @JvmStatic
    fun randomPhat(): Int {
        return Phat[(Math.random() * Phat.size).toInt()]
    }

    var Silvchest: IntArray = intArrayOf(601, 758, 788, 983)

    fun randomSilvchest(): Int {
        return Silvchest[(Math.random() * Silvchest.size).toInt()]
    }

    var fish: IntArray = intArrayOf(385, 385, 379, 379, 379, 379, 379)

    fun randomFish(): Int {
        return fish[(Math.random() * fish.size).toInt()]
    }

    var rat: IntArray = intArrayOf(
        5698, 1305, 3105, 1725, 1704, 1323, 1153, 1115, 1067, 1081, 1157, 1119,
        1069, 1083
    )

    @JvmStatic
    fun randomrat(): Int {
        return rat[(Math.random() * rat.size).toInt()]
    }

    var td: IntArray = intArrayOf(
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        13664,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        15185,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        15195
    )

    fun randomtd(): Int {
        return td[(Math.random() * td.size).toInt()]
    }

    var barrowchest2: IntArray = intArrayOf(
        4708,
        4710,
        4712,
        4714,
        4716,
        4718,
        4720,
        4722,
        4724,
        4726,
        4728,
        4730,
        4732,
        4734,
        4736,
        4740,
        4745,
        4747,
        4749,
        4751,
        4753,
        4755,
        4757,
        4758,
    )

    @JvmStatic
    fun randombarrowchest2(): Int {
        return barrowchest2[(Math.random() * barrowchest2.size).toInt()]
    }

    var well: IntArray = intArrayOf(15195, 15185, 15348, 14520, 15334, 7449, 15346)

    fun randomwell(): Int {
        return well[(Math.random() * well.size).toInt()]
    }

    var soldier: IntArray = intArrayOf(
        ItemIDs.RUNE_CLAWS,
        ItemIDs.RUNE_LONGSWORD,
        ItemIDs.RUNE_HALBERD,
        ItemIDs.RUNE_SCIMITAR,
        ItemIDs.RUNE_2H_SWORD,
        ItemIDs.RUNE_CHAINBODY,
        ItemIDs.RUNE_PLATEBODY,
        ItemIDs.RUNE_MED_HELM,
        ItemIDs.RUNE_PLATESKIRT,
        ItemIDs.RUNE_PLATELEGS,
        ItemIDs.RUNE_BATTLEAXE,
        ItemIDs.RUNE_BOOTS,
        ItemIDs.COINS,
        ItemIDs.RUNE_CROSSBOW,
        ItemIDs.RUNE_JAVELIN,
        ItemIDs.RUNE_KITESHIELD,
        ItemIDs.RUNE_SQ_SHIELD /*ItemIDs.RUNE_KITESHIELD_2, ItemIDs.RUNE_KITESHIELD_3, ItemIDs.RUNE_KITESHIELD_4, ItemIDs.RUNE_KITESHIELD_5, ItemIDs.RUNE_KITESHIELD_6,
            ItemIDs.RUNE_KITESHIELD_7, ItemIDs.RUNE_KITESHIELD_8, ItemIDs.RUNE_KITESHIELD_9, ItemIDs.RUNE_KITESHIELD_10, ItemIDs.RUNE_KITESHIELD_11,
            ItemIDs.RUNE_KITESHIELD_12, ItemIDs.RUNE_KITESHIELD_13, ItemIDs.RUNE_KITESHIELD_14, ItemIDs.RUNE_KITESHIELD_15, ItemIDs.RUNE_KITESHIELD_16, ItemIDs.RUNE_KITESHIELD_17*/
    )

    @JvmStatic
    fun randomsoldier(): Int {
        return soldier[(Math.random() * soldier.size).toInt()]
    }

    var bluedragon: IntArray = intArrayOf(
        2957,
        1050,
        14242,
        4039,
        14238,
        14239,
        14240,
        14241,
        14242,
        1959,
        6857,
        6082,
        4084,
        2526,
        6861,
        7399,
        7398,
        2651,
        6859,
        4565,
        7594,
        10014,
        6863,
        2524,
        4702,
        7400
    )

    @JvmStatic
    fun randombluedragon(): Int {
        return bluedragon[(Math.random() * bluedragon.size).toInt()]
    }


    var MossGiants: IntArray = intArrayOf(
        1179,
        1141,
        1193,
        1389,
        1243,
        1285,
        199,
        201,
        203,
        205,
        207,
        209,
        211,
        213,
        215,
        217,
        219,
        556,
        562,
        557,
        561,
        563,
        562,
        560,
        5323,
        5104,
        5311,
        5292,
        5293,
        5294,
        5281,
        5100,
        5296,
        5105,
        5282,
        4206,
        5298,
        5280,
        5297,
        5299,
        5106,
        5295,
        5301,
        5302,
        5321,
        5300,
        5304,
        5303
    )

    @JvmStatic
    fun randomMossGiants(): Int {
        return MossGiants[(Math.random() * MossGiants.size).toInt()]
    }

    var irondragon: IntArray =
        intArrayOf(2351, 2351, 2351, 2351, 6750, 2351, 2351, 2351, 2351, 6752, 2351, 2351, 2351, 2351)

    @JvmStatic
    fun randomirondragon(): Int {
        return irondragon[(Math.random() * irondragon.size).toInt()]
    }

    var ogre: IntArray = intArrayOf(837, 5018, ItemIDs.COINS)

    @JvmStatic
    fun randomogre(): Int {
        return ogre[(Math.random() * ogre.size).toInt()]
    }

    var chicken: IntArray = intArrayOf(834, ItemIDs.PRESENT)

    @JvmStatic
    fun randomchicken(): Int {
        return chicken[(Math.random() * chicken.size).toInt()]
    }

    var Partyroom: IntArray = intArrayOf(
        ItemIDs.RED_PARTYHAT,
        ItemIDs.YELLOW_PARTYHAT,
        ItemIDs.BLUE_PARTYHAT,
        ItemIDs.GREEN_PARTYHAT,
        ItemIDs.PURPLE_PARTYHAT,
        ItemIDs.WHITE_PARTYHAT,
        1050,
        4716,
        4718,
        4720,
        4722,
        746,
        667,
        2402,
        14507,
        14508,
        14511,
        2633,
        2635,
        2637,
        2978,
        2980,
        2982,
        2984,
        2986,
        2988,
        2990,
        2992,
        2994,
        2957,
        2653,
        2655,
        2659,
        3478,
        2665,
        2661,
        2663,
        2667,
        3479,
        2673,
        2669,
        2671,
        3480,
        35,
        278,
        426,
        428,
        1475,
        4724,
        4728,
        4730,
        4726,
        6570,
        1037,
        1050,
        6857,
        6859,
        6861,
        6863,
        6856,
        6858,
        6860,
        6862,
        6818,
        2591,
        2593,
        2595,
        2597,
        2607,
        2609,
        2611,
        2613,
        2615,
        2617,
        2619,
        2621,
        3473,
        3475,
        3476,
        3669,
        3671,
        3672,
        9004,
        7319,
        7321,
        7323,
        7325,
        7327,
        5527,
        5529,
        5531,
        5533,
        5535,
        5537,
        5539,
        5541,
        5543,
        5545,
        5547,
        5549,
        5551
    )

    @JvmStatic
    fun randomPartyroom(): Int {
        return Partyroom[(Math.random() * Partyroom.size).toInt()]
    }

    var mbox: IntArray = intArrayOf(
        ItemIDs.RED_PARTYHAT,
        ItemIDs.YELLOW_PARTYHAT,
        ItemIDs.BLUE_PARTYHAT,
        ItemIDs.GREEN_PARTYHAT,
        ItemIDs.PURPLE_PARTYHAT,
        ItemIDs.WHITE_PARTYHAT,
        1050,
        4716,
        4718,
        4720,
        4722,
        746,
        667,
        2402,
        14507,
        14508,
        14511,
        2633,
        2635,
        2637,
        2978,
        2980,
        2982,
        2984,
        2986,
        2988,
        2990,
        2992,
        2994,
        2957,
        2653,
        2655,
        2659,
        3478,
        2665,
        2661,
        2663,
        2667,
        3479,
        2673,
        2669,
        2671,
        3480,
        35,
        278,
        426,
        428,
        1475,
        4724,
        4728,
        4730,
        4726,
        6570,
        1037,
        1050,
        6857,
        6859,
        6861,
        6863,
        6856,
        6858,
        6860,
        6862,
        6818,
        2591,
        2593,
        2595,
        2597,
        2607,
        2609,
        2611,
        2613,
        2615,
        2617,
        2619,
        2621,
        3473,
        3475,
        3476,
        3669,
        3671,
        3672,
        9004,
        7319,
        7321,
        7323,
        7325,
        7327,
        5527,
        5529,
        5531,
        5533,
        5535,
        5537,
        5539,
        5541,
        5543,
        5545,
        5547,
        5549,
        5551,
        ItemIDs.A_POWDERED_WIG,
        ItemIDs.FLARED_TROUSERS,
        ItemIDs.PANTALOONS,
        ItemIDs.SLEEPING_CAP,
        ItemIDs.BLACK_ELEGANT_SHIRT,
        ItemIDs.BLACK_ELEGANT_LEGS,
        ItemIDs.RED_ELEGANT_SHIRT,
        ItemIDs.RED_ELEGANT_LEGS,
        ItemIDs.BLUE_ELEGANT_SHIRT,
        ItemIDs.BLUE_ELEGANT_LEGS,
        ItemIDs.GREEN_ELEGANT_SHIRT,
        ItemIDs.GREEN_ELEGANT_LEGS,
        ItemIDs.PURPLE_ELEGANT_SHIRT,
        ItemIDs.PURPLE_ELEGANT_LEGS,
        ItemIDs.WHITE_ELEGANT_BLOUSE,
        ItemIDs.WHITE_ELEGANT_SKIRT,
        ItemIDs.RED_ELEGANT_BLOUSE,
        ItemIDs.RED_ELEGANT_SKIRT,
        ItemIDs.BLUE_ELEGANT_BLOUSE,
        ItemIDs.BLUE_ELEGANT_SKIRT,
        ItemIDs.GREEN_ELEGANT_BLOUSE,
        ItemIDs.GREEN_ELEGANT_SKIRT,
        ItemIDs.PURPLE_ELEGANT_BLOUSE,
        ItemIDs.PURPLE_ELEGANT_SKIRT
    )

    @JvmStatic
    fun randommbox(): Int {
        return mbox[(Math.random() * mbox.size).toInt()]
    }

    var skeleton: IntArray = intArrayOf(
        6137,
        6139,
        6141,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS
    )

    @JvmStatic
    fun randomskeleton(): Int {
        return skeleton[(Math.random() * skeleton.size).toInt()]
    }

    var crawlinghand: IntArray = intArrayOf(
        2615, ItemIDs.RUNE_SCIMITAR, 526, 526, 526, 526, 526, 526, 526, 526, 526, 526, 526, 526,
        526, 526
    )

    @JvmStatic
    fun randomcrawlinghand(): Int {
        return crawlinghand[(Math.random() * crawlinghand.size).toInt()]
    }

    var Keys: IntArray = intArrayOf(
        5698,
        1305,
        3105,
        1725,
        1704,
        1323,
        1153,
        1115,
        1067,
        1081,
        1157,
        1119,
        1069,
        1083,
        ItemIDs.RUNE_CLAWS,
        ItemIDs.RUNE_LONGSWORD,
        ItemIDs.RUNE_HALBERD,
        ItemIDs.RUNE_SCIMITAR,
        ItemIDs.RUNE_2H_SWORD,
        ItemIDs.RUNE_CHAINBODY,
        ItemIDs.RUNE_PLATEBODY,
        ItemIDs.RUNE_MED_HELM,
        ItemIDs.RUNE_PLATESKIRT,
        ItemIDs.RUNE_PLATELEGS,
        ItemIDs.RUNE_BATTLEAXE,
        ItemIDs.RUNE_BOOTS,
        2957,
        1050,
        4039,
        1959,
        6857,
        6082,
        4084,
        2526,
        6861,
        7399,
        7398,
        2651,
        6859,
        4565,
        7594,
        10014,
        6863,
        2524,
        4702,
        7400,
        ItemIDs.RED_PARTYHAT,
        ItemIDs.YELLOW_PARTYHAT,
        ItemIDs.BLUE_PARTYHAT,
        ItemIDs.GREEN_PARTYHAT,
        ItemIDs.PURPLE_PARTYHAT,
        ItemIDs.WHITE_PARTYHAT,
        1050,
        15334,
        15336,
        15333,
        15335,
        4716,
        4718,
        4720,
        4722,
        14507,
        14508,
        14511,
        2633,
        2635,
        2637,
        2978,
        2980,
        2982,
        2984,
        2986,
        2988,
        2990,
        2992,
        2994,
        2957,
        2653,
        2655,
        2659,
        3478,
        2665,
        2661,
        2663,
        2667,
        3479,
        2673,
        2669,
        2671,
        3480,
        4724,
        4728,
        4730,
        4726,
        6570,
        1037,
        1050,
        6857,
        6859,
        6861,
        6863,
        6856,
        6858,
        6860,
        6862,
        6818,
        4119,
        4121,
        4123,
        4125,
        4127,
        4129,
        ItemIDs.RUNE_BOOTS,
        1725,
        1704,
        ItemIDs.RED_PARTYHAT,
        3105,
        1305,
        5698,
        4587,
        4726,
        7386,
        7394,
        7390,
        1037,
        1989,
        6666,
        2944,
        6779,
        9093,
        8013,
        8014,
        8015,
        8016,
        8017,
        8018,
        8019,
        4565,
        1959,
        1053,
        1055,
        1057,
        ItemIDs.BLUE_PARTYHAT,
        ItemIDs.YELLOW_PARTYHAT,
        ItemIDs.GREEN_PARTYHAT,
        ItemIDs.RED_PARTYHAT,
        ItemIDs.PURPLE_PARTYHAT,
        1050,
        1641,
        2633,
        2635,
        2637,
        2978,
        2980,
        2982,
        2984,
        2986,
        2988,
        2990,
        2992,
        2994,
        2957,
        2653,
        2655,
        2659,
        3478,
        2665,
        2661,
        2663,
        2667,
        3479,
        2673,
        2669,
        2671,
        3480,
        4724,
        4728,
        4730,
        4726,
        6570,
        1037,
        1050,
        6857,
        6859,
        6861,
        6863,
        6856,
        6858,
        6860,
        6862,
        6818,
        1641,
        ItemIDs.RED_PARTYHAT,
        ItemIDs.YELLOW_PARTYHAT,
        ItemIDs.BLUE_PARTYHAT,
        ItemIDs.GREEN_PARTYHAT,
        ItemIDs.PURPLE_PARTYHAT,
        ItemIDs.WHITE_PARTYHAT,
        8000,
        10560
    )

    fun randomKeys(): Int {
        return Keys[(Math.random() * Keys.size).toInt()]
    }

    var cavebug: IntArray = intArrayOf(
        4119, 4121, 4123, 4125, 4127, 4129, ItemIDs.RUNE_BOOTS, 526, 526, 526, 526, 526, 526,
        526, 526, 526, 526, 526, 526, 526, 526, 526, 526, 526, 526
    )

    @JvmStatic
    fun randomcavebug(): Int {
        return cavebug[(Math.random() * cavebug.size).toInt()]
    }

    var jelly: IntArray = intArrayOf(
        14860, 6809, 526, 526, 526, 526, 526, 526, 526, 526, 526, 526, 526, 526,
        526, 526, 526, 526, 526, 526, 526, 526, 526, 526, 526, 526, 526, 526,
        526, 526
    )

    @JvmStatic
    fun randomjelly(): Int {
        return jelly[(Math.random() * jelly.size).toInt()]
    }

    var aberrantspecter: IntArray = intArrayOf(
        3840, 3842, 3844, 526, 526, 526, 526, 526, 526, 526, 526, 526, 526, 526,
        526, 526, 526, 526, 526, 526, 526, 526, 526, 526, 526, 526, 526, 526,
        526
    )

    @JvmStatic
    fun randomaberrantspecter(): Int {
        return aberrantspecter[(Math.random() * aberrantspecter.size).toInt()]
    }

    var abyssaldemon: IntArray = intArrayOf(
        4151, 526, 526, 526, 526, 526, 526, 526, 526, 526, 526, 526, 526, 526,
        526, 526, 526, 526, 526, 526, 526, 526, 526, 526, 526
    )

    @JvmStatic
    fun randomabyssaldemon(): Int {
        return abyssaldemon[(Math.random() * abyssaldemon.size).toInt()]
    }

    var darkbeast: IntArray = intArrayOf(
        6818, 11192, 526, 526, 526, 526, 526, 526, 526, 526, 526, 526, 526, 526,
        526, 526, 526, 526, 526, 526, 526, 526, 526, 526, 526, 526, 526, 526,
        526, 526, 526, 526, 526, 526, 526, 526, 526, 526, 526, 526, 526, 526,
        526, 526, 526, 526, 526, 526, 526, 526, 526, 526, 526, 526, 526, 526,
        526, 526, 526, 526, 526, 526, 526, 526, 526, 526, 526, 526, 526, 526,
        526, 526, 526, 526, 526, 526, 526, 526
    )

    @JvmStatic
    fun randomdarkbeast(): Int {
        return darkbeast[(Math.random() * darkbeast.size).toInt()]
    }

    var barbarian: IntArray =
        intArrayOf(1725, 1704, ItemIDs.RED_PARTYHAT, 3105, 1305, 5698, 4587, 4726, 7386, 7394, 7390, ItemIDs.COINS)

    @JvmStatic
    fun randombarbarian(): Int {
        return barbarian[(Math.random() * barbarian.size).toInt()]
    }

    var fishy: IntArray = intArrayOf(
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        35,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        773,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS
    )

    @JvmStatic
    fun randomfishy(): Int {
        return fishy[(Math.random() * fishy.size).toInt()]
    }

    var Dagannoths: IntArray = intArrayOf(
        1037,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        1989,
        6666,
        2944,
        6779,
        9093,
        8013,
        8014,
        13444,
        13445,
        13446,
        13447,
        13448,
        13449,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        13450,
        13451,
        13452,
        13453,
        13454,
        13455,
        13456,
        13457,
        13558,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        13459,
        13460,
        13461,
        13462,
        13463,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        13464,
        13465,
        13466,
        13467,
        13468,
        13469,
        13470,
        13471,
        13472,
        13473,
        13474,
        13475,
        13476,
        13477,
        13478,
        13479,
        13480,
        13481,
        8015,
        8016,
        8017,
        8018,
        8019,
        4565,
        1959,
        1053,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        1055,
        1057,
        ItemIDs.BLUE_PARTYHAT,
        ItemIDs.YELLOW_PARTYHAT,
        ItemIDs.GREEN_PARTYHAT,
        ItemIDs.RED_PARTYHAT,
        ItemIDs.PURPLE_PARTYHAT,
        1050
    )

    @JvmStatic
    fun randomDagannoths(): Int {
        return Dagannoths[(Math.random() * Dagannoths.size).toInt()]
    }

    var unicorn: IntArray = intArrayOf(
        6966,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS
    )

    @JvmStatic
    fun randomunicorn(): Int {
        return unicorn[(Math.random() * unicorn.size).toInt()]
    }

    var battlemagesara: IntArray = intArrayOf(
        14507,
        14508,
        14513,
        5698,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS
    )

    @JvmStatic
    fun randombattlemagesara(): Int {
        return battlemagesara[(Math.random() * battlemagesara.size).toInt()]
    }

    var battlemagezammy: IntArray = intArrayOf(
        14507,
        14508,
        14512,
        5698,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS
    )

    @JvmStatic
    fun randombattlemagezammy(): Int {
        return battlemagezammy[(Math.random() * battlemagezammy.size).toInt()]
    }

    var battlemageguthix: IntArray = intArrayOf(
        14507,
        14508,
        14511,
        5698,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS
    )

    @JvmStatic
    fun randombattlemageguthix(): Int {
        return battlemageguthix[(Math.random() * battlemageguthix.size).toInt()]
    }

    var troll: IntArray = intArrayOf(
        3741,
        3741,
        3741,
        3741,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS,
        ItemIDs.COINS
    )

    @JvmStatic
    fun randomtroll(): Int {
        return troll[(Math.random() * troll.size).toInt()]
    }

    var KQ: IntArray = intArrayOf(
        2633, 2635, 2637, 2978, 2980, 2982, 2984, 2986, 2988, 2990, 2992, 2994,
        2957, 2653, 2655, 2659, 3478, 2665, 2661, 2663, 2667, 3479, 2673, 2669,
        2671, 3480, 4724, 4728, 4730, 4726, 6570, 1037, 1050, 6857, 6859, 6861,
        6863, 6856, 6858, 6860, 6862, 6818
    )

    @JvmStatic
    fun randomKQ(): Int {
        return KQ[(Math.random() * KQ.size).toInt()]
    }

    var Jogre: IntArray = intArrayOf(4587, 15352, 7158, 1149, 4151, 5698, 1377, 1305, 1434)

    fun randomJogre(): Int {
        return Jogre[(Math.random() * Jogre.size).toInt()]
    }

    var Ice_giant: IntArray = intArrayOf(1543, 1546, 1545, 1548)

    @JvmStatic
    fun randomIce_giant(): Int {
        return Ice_giant[(Math.random() * Ice_giant.size).toInt()]
    }

    var Dagannoth_Rex: IntArray =
        intArrayOf(532, 532, 532, 532, 532, 532, 532, 532, 532, 532, 532, 532, 532, 15348, 15349, 532, 532, 532)

    fun randomDagannoth_Rex(): Int {
        return Dagannoth_Rex[(Math.random() * Dagannoth_Rex.size).toInt()]
    }

    var Dagannoth_Prime: IntArray =
        intArrayOf(532, 532, 532, 532, 532, 532, 532, 532, 532, 532, 532, 532, 15350, 15334, 532, 532, 532)

    fun randomDagannoth_Prime(): Int {
        return Dagannoth_Prime[(Math.random() * Dagannoth_Prime.size).toInt()]
    }

    var Dagannoth_Supreme: IntArray =
        intArrayOf(532, 532, 532, 532, 532, 532, 532, 532, 532, 532, 532, 532, 15185, 15195, 532, 532, 532)

    fun randomDagannoth_Supreme(): Int {
        return Dagannoth_Supreme[(Math.random() * Dagannoth_Supreme.size).toInt()]
    }

    var Flambeed: IntArray = intArrayOf(6104, 991)

    @JvmStatic
    fun randomFlambeed(): Int {
        return Flambeed[(Math.random() * Flambeed.size).toInt()]
    }

    var Black_Demon: IntArray =
        intArrayOf(532, 532, 532, 532, 532, 532, 532, 532, 532, 532, 532, 14503, 14505, 14504, 532, 532, 532)

    @JvmStatic
    fun randomBlack_Demon(): Int {
        return Black_Demon[(Math.random() * Black_Demon.size).toInt()]
    }

    var Skeleton_Hellhound: IntArray =
        intArrayOf(532, 532, 532, 532, 532, 532, 532, 532, 532, 532, 14507, 14506, 14508, 14509, 532, 532, 532)

    @JvmStatic
    fun randomSkeleton_Hellhound(): Int {
        return Skeleton_Hellhound[(Math.random() * Skeleton_Hellhound.size).toInt()]
    }

    var Agrith_Naar: IntArray =
        intArrayOf(532, 532, 532, 532, 532, 532, 532, 532, 532, 532, 532, 532, 532, 7449, 3140, 532, 532, 532)

    @JvmStatic
    fun randomAgrith_Naar(): Int {
        return Agrith_Naar[(Math.random() * Agrith_Naar.size).toInt()]
    }


    var Arzinian_Being_of_Bordanzan: IntArray =
        intArrayOf(532, 532, 532, 532, 532, 532, 532, 532, 532, 532, 532, 532, 15345, 14521, 15346, 532, 532, 532)

    @JvmStatic
    fun randomArzinian_Being_of_Bordanzan(): Int {
        return Arzinian_Being_of_Bordanzan[(Math.random() * Arzinian_Being_of_Bordanzan.size).toInt()]
    }

    var KBD: IntArray = intArrayOf(15352, 15334, 4585, 14519, 4087, 15195)

    fun randomKBD(): Int {
        return KBD[(Math.random() * KBD.size).toInt()]
    }
}
