public class MenuHandler {

    public void attackMenu(int a) {
        client p = (client) PlayerHandler.players[a];

        p.getPA().sendQuest("@whi@Attack", 8716);
        p.getPA().sendQuest("@whi@Level", 8718);
        p.getPA().sendQuest("@whi@Advancement", 8719);
        p.getPA().sendQuest("@cya@1", 8720);
        p.getPA().sendQuest("@cya@1", 8721);
        p.getPA().sendQuest("@cya@5", 8722);
        p.getPA().sendQuest("@cya@10", 8723);
        p.getPA().sendQuest("@cya@20", 8724);
        p.getPA().sendQuest("@cya@30", 8725);
        p.getPA().sendQuest("@cya@40", 8726);
        p.getPA().sendQuest("@cya@60", 8727);
        p.getPA().sendQuest("@cya@70", 8728);
        p.getPA().sendQuest("@cya@70", 8729);
        p.getPA().sendQuest(" ", 8730);
        p.getPA().sendQuest("@cya@Bronze", 8760);
        p.getPA().sendQuest("@cya@Iron", 8761);
        p.getPA().sendQuest("@cya@Steel", 8762);
        p.getPA().sendQuest("@cya@Black", 8763);
        p.getPA().sendQuest("@cya@Mithril", 8764);
        p.getPA().sendQuest("@cya@Adamentite", 8765);
        p.getPA().sendQuest("@cya@Rune", 8766);
        p.getPA().sendQuest("@cya@Dragon", 8767);
        p.getPA().sendQuest("@cya@Barrows", 8768);
        p.getPA().sendQuest("@cya@Abyssal", 8769);
        p.getPA().sendQuest(" ", 8770);
        p.getPA().sendQuest("Attack", 8846);
        p.getPA().sendQuest(" ", 8849);
        p.getPA().sendQuest("Defense", 8823);
        p.getPA().sendQuest("Ranged", 8824);
        p.getPA().sendQuest("Magic", 8827);
        p.getPA().sendQuest(" ", 8837);
        p.getPA().sendQuest(" ", 8840);
        p.getPA().sendQuest(" ", 8843);
        p.getPA().sendQuest(" ", 8859);
        p.getPA().sendQuest(" ", 8862);
        p.getPA().sendQuest(" ", 8865);
        p.getPA().sendQuest(" ", 15303);
        p.getPA().sendQuest(" ", 15306);
        p.getPA().sendQuest(" ", 15309);
        p.clearQuestInterface();
        p.getPA().sendFrame246(8715, 700, 4587);
        p.getPA().showInterface(8714);
        p.flushOutStream();
    }

    public void defenseMenu(int a) {
        client p = (client) PlayerHandler.players[a];

        p.getPA().sendQuest("@whi@Defense", 8716);
        p.getPA().sendQuest("@whi@Level", 8718);
        p.getPA().sendQuest("@whi@Advancement", 8719);
        p.getPA().sendQuest("@cya@1", 8720);
        p.getPA().sendQuest("@cya@1", 8721);
        p.getPA().sendQuest("@cya@5", 8722);
        p.getPA().sendQuest("@cya@10", 8723);
        p.getPA().sendQuest("@cya@20", 8724);
        p.getPA().sendQuest("@cya@30", 8725);
        p.getPA().sendQuest("@cya@40", 8726);
        p.getPA().sendQuest("@cya@50", 8727);
        p.getPA().sendQuest("@cya@60", 8728);
        p.getPA().sendQuest("@cya@70", 8729);
        p.getPA().sendQuest(" ", 8730);
        p.getPA().sendQuest("@cya@Bronze", 8760);
        p.getPA().sendQuest("@cya@Iron", 8761);
        p.getPA().sendQuest("@cya@Steel", 8762);
        p.getPA().sendQuest("@cya@Black", 8763);
        p.getPA().sendQuest("@cya@Mithril", 8764);
        p.getPA().sendQuest("@cya@Adamentite", 8765);
        p.getPA().sendQuest("@cya@Rune", 8766);
        p.getPA().sendQuest("@cya@Granite", 8767);
        p.getPA().sendQuest("@cya@Dragon", 8768);
        p.getPA().sendQuest("@cya@Barrows", 8769);
        p.getPA().sendQuest(" ", 8770);
        p.getPA().sendQuest("Attack", 8846);
        p.getPA().sendQuest(" ", 8849);
        p.getPA().sendQuest("Defense", 8823);
        p.getPA().sendQuest("Ranged", 8824);
        p.getPA().sendQuest("Magic", 8827);
        p.getPA().sendQuest(" ", 8837);
        p.getPA().sendQuest(" ", 8840);
        p.getPA().sendQuest(" ", 8843);
        p.getPA().sendQuest(" ", 8859);
        p.getPA().sendQuest(" ", 8862);
        p.getPA().sendQuest(" ", 8865);
        p.getPA().sendQuest(" ", 15303);
        p.getPA().sendQuest(" ", 15306);
        p.getPA().sendQuest(" ", 15309);
        p.clearQuestInterface();
        p.getPA().sendFrame246(8715, 600, 1187);
        p.getPA().showInterface(8714);
        p.flushOutStream();
    }

    public void rangeMenu(int a) {
        client p = (client) PlayerHandler.players[a];

        p.getPA().sendQuest("@whi@Ranged", 8716);
        p.getPA().sendQuest("@whi@Level", 8718);
        p.getPA().sendQuest("@whi@Advancement", 8719);
        p.getPA().sendQuest("@cya@1", 8720);
        p.getPA().sendQuest("@cya@1", 8721);
        p.getPA().sendQuest("@cya@5", 8722);
        p.getPA().sendQuest("@cya@20", 8723);
        p.getPA().sendQuest("@cya@30", 8724);
        p.getPA().sendQuest("@cya@40", 8725);
        p.getPA().sendQuest("@cya@50", 8726);
        p.getPA().sendQuest("@cya@70", 8727);
        p.getPA().sendQuest(" ", 8728);
        p.getPA().sendQuest(" ", 8729);
        p.getPA().sendQuest(" ", 8730);
        p.getPA().sendQuest("@cya@Short Bow", 8760);
        p.getPA().sendQuest("@cya@Long Bow", 8761);
        p.getPA().sendQuest("@cya@Oak Bows", 8762);
        p.getPA().sendQuest("@cya@Willow Bows", 8763);
        p.getPA().sendQuest("@cya@Maple Bows", 8764);
        p.getPA().sendQuest("@cya@Yew Bows", 8765);
        p.getPA().sendQuest("@cya@Magic Bows", 8766);
        p.getPA().sendQuest("@cya@Crystal Bow", 8767);
        p.getPA().sendQuest(" ", 8768);
        p.getPA().sendQuest(" ", 8769);
        p.getPA().sendQuest(" ", 8770);
        p.getPA().sendQuest("Attack", 8846);
        p.getPA().sendQuest(" ", 8849);
        p.getPA().sendQuest("Defense", 8823);
        p.getPA().sendQuest("Ranged", 8824);
        p.getPA().sendQuest("Magic", 8827);
        p.getPA().sendQuest(" ", 8837);
        p.getPA().sendQuest(" ", 8840);
        p.getPA().sendQuest(" ", 8843);
        p.getPA().sendQuest(" ", 8859);
        p.getPA().sendQuest(" ", 8862);
        p.getPA().sendQuest(" ", 8865);
        p.getPA().sendQuest(" ", 15303);
        p.getPA().sendQuest(" ", 15306);
        p.getPA().sendQuest(" ", 15309);
        p.clearQuestInterface();
        p.getPA().sendFrame246(8715, 600, 4212);
        p.getPA().showInterface(8714);
        p.flushOutStream();
    }

    public void mageMenu(int a) {
        client p = (client) PlayerHandler.players[a];

        p.getPA().sendQuest("@whi@Magic", 8716);
        p.getPA().sendQuest("@whi@Level", 8718);
        p.getPA().sendQuest("@whi@Advancement", 8719);
        p.getPA().sendQuest("@cya@NA", 8720);
        p.getPA().sendQuest("@cya@20", 8721);
        p.getPA().sendQuest(" ", 8722);
        p.getPA().sendQuest(" ", 8723);
        p.getPA().sendQuest(" ", 8724);
        p.getPA().sendQuest(" ", 8725);
        p.getPA().sendQuest(" ", 8726);
        p.getPA().sendQuest(" ", 8727);
        p.getPA().sendQuest(" ", 8728);
        p.getPA().sendQuest(" ", 8729);
        p.getPA().sendQuest(" ", 8730);
        p.getPA().sendQuest("@cya@See Spell Book", 8760);
        p.getPA().sendQuest("@cya@Mystic Armour", 8761);
        p.getPA().sendQuest(" ", 8762);
        p.getPA().sendQuest(" ", 8763);
        p.getPA().sendQuest(" ", 8764);
        p.getPA().sendQuest(" ", 8765);
        p.getPA().sendQuest(" ", 8766);
        p.getPA().sendQuest(" ", 8767);
        p.getPA().sendQuest(" ", 8768);
        p.getPA().sendQuest(" ", 8769);
        p.getPA().sendQuest(" ", 8770);
        p.getPA().sendQuest("Attack", 8846);
        p.getPA().sendQuest(" ", 8849);
        p.getPA().sendQuest("Defense", 8823);
        p.getPA().sendQuest("Ranged", 8824);
        p.getPA().sendQuest("Magic", 8827);
        p.getPA().sendQuest(" ", 8837);
        p.getPA().sendQuest(" ", 8840);
        p.getPA().sendQuest(" ", 8843);
        p.getPA().sendQuest(" ", 8859);
        p.getPA().sendQuest(" ", 8862);
        p.getPA().sendQuest(" ", 8865);
        p.getPA().sendQuest(" ", 15303);
        p.getPA().sendQuest(" ", 15306);
        p.getPA().sendQuest(" ", 15309);
        p.clearQuestInterface();
        p.getPA().sendFrame246(8715, 600, 560);
        p.getPA().showInterface(8714);
        p.flushOutStream();
    }

    public void prayMenu(int a) {
        client p = (client) PlayerHandler.players[a];

        p.getPA().sendQuest("@whi@Prayer", 8716);
        p.getPA().sendQuest("@whi@Level", 8718);
        p.getPA().sendQuest("@whi@Advancement", 8719);
        p.getPA().sendQuest("@cya@NA", 8720);
        p.getPA().sendQuest(" ", 8721);
        p.getPA().sendQuest(" ", 8722);
        p.getPA().sendQuest(" ", 8723);
        p.getPA().sendQuest(" ", 8724);
        p.getPA().sendQuest(" ", 8725);
        p.getPA().sendQuest(" ", 8726);
        p.getPA().sendQuest(" ", 8727);
        p.getPA().sendQuest(" ", 8728);
        p.getPA().sendQuest(" ", 8729);
        p.getPA().sendQuest(" ", 8730);
        p.getPA().sendQuest("@cya@See Prayer Book", 8760);
        p.getPA().sendQuest(" ", 8761);
        p.getPA().sendQuest(" ", 8762);
        p.getPA().sendQuest(" ", 8763);
        p.getPA().sendQuest(" ", 8764);
        p.getPA().sendQuest(" ", 8765);
        p.getPA().sendQuest(" ", 8766);
        p.getPA().sendQuest(" ", 8767);
        p.getPA().sendQuest(" ", 8768);
        p.getPA().sendQuest(" ", 8769);
        p.getPA().sendQuest(" ", 8770);
        p.getPA().sendQuest("Attack", 8846);
        p.getPA().sendQuest(" ", 8849);
        p.getPA().sendQuest("Defense", 8823);
        p.getPA().sendQuest("Ranged", 8824);
        p.getPA().sendQuest("Magic", 8827);
        p.getPA().sendQuest(" ", 8837);
        p.getPA().sendQuest(" ", 8840);
        p.getPA().sendQuest(" ", 8843);
        p.getPA().sendQuest(" ", 8859);
        p.getPA().sendQuest(" ", 8862);
        p.getPA().sendQuest(" ", 8865);
        p.getPA().sendQuest(" ", 15303);
        p.getPA().sendQuest(" ", 15306);
        p.getPA().sendQuest(" ", 15309);
        p.clearQuestInterface();
        p.getPA().sendFrame246(8715, 600, 3840);
        p.getPA().showInterface(8714);
        p.flushOutStream();
    }

    public void runecraftMenu(int a) {
        client p = (client) PlayerHandler.players[a];

        p.getPA().sendQuest("@whi@Runecrafting", 8716);
        p.getPA().sendQuest("@whi@Level", 8718);
        p.getPA().sendQuest("@whi@Advancement", 8719);
        p.getPA().sendQuest("@cya@1", 8720);
        p.getPA().sendQuest("@cya@2", 8721);
        p.getPA().sendQuest("@cya@5 ", 8722);
        p.getPA().sendQuest("@cya@9", 8723);
        p.getPA().sendQuest("@cya@14", 8724);
        p.getPA().sendQuest("@cya@20", 8725);
        p.getPA().sendQuest("@cya@27", 8726);
        p.getPA().sendQuest("@cya@35", 8727);
        p.getPA().sendQuest("@cya@44", 8728);
        p.getPA().sendQuest("@cya@54", 8729);
        p.getPA().sendQuest("@cya@65", 8730);
        p.getPA().sendQuest("@cya@Air Runes", 8760);
        p.getPA().sendQuest("@cya@Mind Runes", 8761);
        p.getPA().sendQuest("@cya@Water Runes", 8762);
        p.getPA().sendQuest("@cya@Earth Runes", 8763);
        p.getPA().sendQuest("@cya@Fire Runes", 8764);
        p.getPA().sendQuest("@cya@Body Runes", 8765);
        p.getPA().sendQuest("@cya@Cosmic Runes", 8766);
        p.getPA().sendQuest("@cya@Chaos Runes", 8767);
        p.getPA().sendQuest("@cya@Nature Runes", 8768);
        p.getPA().sendQuest("@cya@Law Runes", 8769);
        p.getPA().sendQuest("@cya@Death Runes", 8770);
        p.getPA().sendQuest("Attack", 8846);
        p.getPA().sendQuest(" ", 8849);
        p.getPA().sendQuest("Defense", 8823);
        p.getPA().sendQuest("Ranged", 8824);
        p.getPA().sendQuest("Magic", 8827);
        p.getPA().sendQuest(" ", 8837);
        p.getPA().sendQuest(" ", 8840);
        p.getPA().sendQuest(" ", 8843);
        p.getPA().sendQuest(" ", 8859);
        p.getPA().sendQuest(" ", 8862);
        p.getPA().sendQuest(" ", 8865);
        p.getPA().sendQuest(" ", 15303);
        p.getPA().sendQuest(" ", 15306);
        p.getPA().sendQuest(" ", 15309);
        p.clearQuestInterface();
        p.getPA().sendFrame246(8715, 600, 1458);
        p.getPA().showInterface(8714);
        p.flushOutStream();
    }

    public void agilityMenu(int a) {
        client p = (client) PlayerHandler.players[a];

        p.getPA().sendQuest("@whi@Agility", 8716);
        p.getPA().sendQuest("@whi@Level", 8718);
        p.getPA().sendQuest("@whi@Advancement", 8719);
        p.getPA().sendQuest("@cya@1", 8720);
        p.getPA().sendQuest("@cya@30", 8721);
        p.getPA().sendQuest(" ", 8722);
        p.getPA().sendQuest(" ", 8723);
        p.getPA().sendQuest(" ", 8724);
        p.getPA().sendQuest(" ", 8725);
        p.getPA().sendQuest(" ", 8726);
        p.getPA().sendQuest(" ", 8727);
        p.getPA().sendQuest(" ", 8728);
        p.getPA().sendQuest(" ", 8729);
        p.getPA().sendQuest(" ", 8730);
        p.getPA().sendQuest("@cya@Gnome Course", 8760);
        p.getPA().sendQuest("@cya@Werewolf Course ", 8761);
        p.getPA().sendQuest(" ", 8762);
        p.getPA().sendQuest(" ", 8763);
        p.getPA().sendQuest(" ", 8764);
        p.getPA().sendQuest(" ", 8765);
        p.getPA().sendQuest(" ", 8766);
        p.getPA().sendQuest(" ", 8767);
        p.getPA().sendQuest(" ", 8768);
        p.getPA().sendQuest(" ", 8769);
        p.getPA().sendQuest(" ", 8770);
        p.getPA().sendQuest("Attack", 8846);
        p.getPA().sendQuest(" ", 8849);
        p.getPA().sendQuest("Defense", 8823);
        p.getPA().sendQuest("Ranged", 8824);
        p.getPA().sendQuest("Magic", 8827);
        p.getPA().sendQuest(" ", 8837);
        p.getPA().sendQuest(" ", 8840);
        p.getPA().sendQuest(" ", 8843);
        p.getPA().sendQuest(" ", 8859);
        p.getPA().sendQuest(" ", 8862);
        p.getPA().sendQuest(" ", 8865);
        p.getPA().sendQuest(" ", 15303);
        p.getPA().sendQuest(" ", 15306);
        p.getPA().sendQuest(" ", 15309);
        p.clearQuestInterface();
        p.getPA().sendFrame246(8715, 600, 3107);
        p.getPA().showInterface(8714);
        p.flushOutStream();
    }
}
