public class soundList {
    public static final int COOK_ITEM = 618;          // Cooking fire sizzle
    public static final int MINING_ORE = 1315;        // Pickaxe hit rock
    public static final int ANVIL = 468;              // Anvil clang
    public static final int BONE_BURY = 380;
    public static final int FIRE_LIGHT = 375;
    public static final int FIRE_SUCCESSFUL = 608;
    public static final int FIRST_ATTEMPT = 2584;     // Sound played on first skilling attempt (generic)
    public static final int TREE_CUT_BEGIN = 471;
    public static final int TREE_CUTTING = 472;
    public static final int TREE_EMPTY = 473;
    public static final int FISHING = 289;
    public static final int START_FLY_FISHING = 377;
    public static final int FLY_FISHING = 378;
    public static final int RUNECRAFTING = 481;
    public static final int RAKE_WEEDS = 1323;
    public static final int SMELTING_ORE = 469;
    public static final int SMITHING_ANVIL = 468;
    public static final int STUNNED = 458;
    public static final int PESTLE_MORTAR = 373;
    public static final int PROSPECTING = 431;
    public static final int CUT_GEM = 464;
    public static final int STALL_THIEF = 2582;       // Confirmed correct for stalls (rustle)

    public static final int LEVEL_UP_COOKING = 579;
    public static final int LEVEL_UP_FIREMAKING = 582;
    public static final int LEVEL_UP_RUNECRAFTING = 593;
    public static final int LEVEL_UP_THIEVING = 590;
    public static final int LEVEL_UP_RANGED = 588;
    public static final int LEVEL_UP_FLETCHING = 586;
    public static final int LEVEL_UP_SMITHING = 591;
    public static final int LEVEL_UP_PRAYER = 587;
    public static final int LEVEL_UP_FISHING = 580;
    public static final int LEVEL_UP_MAGIC = 585;
    public static final int LEVEL_UP_DEFENCE = 583;
    public static final int LEVEL_UP_HERBLORE = 581;
    public static final int LEVEL_UP_ATTACK = 578;
    public static final int LEVEL_UP_WOODCUTTING = 594;
    public static final int LEVEL_UP_MINING = 584;
    public static final int LEVEL_UP_CRAFTING = 592;
    public static final int LEVEL_UP_STRENGTH = 589;
    public static final int PLAYER_DEATH_SOUND = 75;  // Still valid (OSRS uses this for PvP)
    public static final int PROTECT_MELEE = 433;
    public static final int PROTECT_MAGIC = 438;
    public static final int PROTECT_RANGE = 444;
    public static final int NO_PRAY = 435;
    public static final int PRAYER_TOO_LOW = 447;
    public static final int MAGE_SPLASH = 193;
    public static final int MAGE_FAIL = 941;
    public static final int TELEBLOCK_CAST = 1185;
    public static final int TELEBLOCK_HIT = 1183;
    public static final int LOW_ALCHEMY = 224;
    public static final int HIGH_ALCHEMY = 223;
    public static final int ICE_BLITZ = 1110;
    public static final int TELEPORT = 202;
    public static final int BLOOD_RUSH = 984;
    public static final int BLOOD_BLITZ = 985;
    public static final int ANCIENT_BLOOD = 986;          // Custom? Shared splash?
    public static final int BLOOD_RUSH_SPLASH = 991;
    public static final int WIND_STRIKE = 992;
    public static final int SUPERHEAT = 217;
    public static final int SUPERHEAT_FAIL = 218;
    public static final int BONES_TO_BANANAS = 227;
    public static final int SHOOT_ARROW = 370;
    public static final int FOOD_EAT = 2393;
    public static final int DRINK = 334;
    public static final int ITEM_PICKUP = 2586;
    public static final int ITEM_DROP = 2739;
    public static final int EXPLODING_ROCK = 429;
    public static final int EXPLODING_ROCK_2 = 432;
    public static final int KISS_FROG = 652;

    public static final int DUEL_WON = 77;
    public static final int DUEL_LOST = 76;
    public static final int DITCH = 2462;
    public static final int JUMPING_STONES = 455;
    public static final int PICKABLE = 358;
    public static final int SLASH_WEB = 237;
    public static final int OPEN_DOOR = 326;
    public static final int OPEN_GATE = 1328;
    public static final int EMPTY = 334;

}
